### ISSUE TITLE
Dynamic pore network model

### ISSUE THREAD

**Issue by chenmingqiangqiang** [mhgolestan/MatlabPNM#1]
Can this code be used for realistic pore network model? And do you have a dynamic pore network model written in matlab?

**Comment by mhgolestan** [comment]
Yes it reads in pore network files in statoil protocol. we are still working on the dynamic mode on the code. any collaboration is accepted!

**Comment by Yang-program** [comment]
Hi, can this code be used for the situations in which the pore radii and permeaiblity change with time because of biomass growth or mineral deposition and dissolution?

**Comment by chenmingqiangqiang** [comment]
Dear Professor,
  Thank you very much for your e-mail to notify me. I'm so grateful of you. Since I also major in pore network model, I downloaded your code online. However, I didn't konw how to perform it. Can you tell me how to perform it at your convenicence? And would you mind sending me your matlab coede including the pore network extraction, primary drainage, imbibition and the situtuations in which the pore radii and permeaiblity change with time because of biomass growth or mineral deposition and dissolution? I'll be grateful for that. Hope to receive your reply.
Best wishes for you.
Yours sincerely,
Mingqiang Chen 
------------------ 原始邮件 ------------------
发件人: "Yang-program"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 中午11:28
收件人: "mhgolestan/MatlabPNM"<MatlabPNM@noreply.github.com>;
抄送: "549135449"<549135449@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mhgolestan/MatlabPNM] Dynamic pore network model (#1)




Hi, can this code be used for the situations in which the pore radii and permeaiblity change with time because of biomass growth or mineral deposition and dissolution?

**Comment by mhgolestan** [comment]
> Dear Professor, Thank you very much for your e-mail to notify me. I'm so grateful of you. Since I also major in pore network model, I downloaded your code online. However, I didn't konw how to perform it. Can you tell me how to perform it at your convenicence? And would you mind sending me your matlab coede including the pore network extraction, primary drainage, imbibition and the situtuations in which the pore radii and permeaiblity change with time because of biomass growth or mineral deposition and dissolution? I'll be grateful for that. Hope to receive your reply. Best wishes for you. Yours sincerely, Mingqiang Chen ------------------ 原始邮件 ------------------ 发件人: "Yang-program"<notifications@github.com>; 发送时间: 2019年7月24日(星期三) 中午11:28 收件人: "mhgolestan/MatlabPNM"<MatlabPNM@noreply.github.com>; 抄送: "549135449"<549135449@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [mhgolestan/MatlabPNM] Dynamic pore network model (#1) Hi, can this code be used for the situations in which the pore radii and permeaiblity change with time because of biomass growth or mineral deposition and dissolution? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
