### ISSUE TITLE
network extracting

### ISSUE THREAD

**Issue by xu-kai-xu** [mhgolestan/MatlabPNM#8]
wish you to supply some network extracting methods

**Comment by mhgolestan** [comment]
At the moment, the package does not contain any network extraction algorithm. but it reads in pore network files in Statoil protocol

**Comment by ZhouChuanyou** [comment]
Hi, Professor Mohammad, the first released version MatlabPNM-1.0.0 is really great for understanding the pore network. But I find an unreasonable calculation code in totalPoreVol.m line 13: fprintf('Porosity of the model is: %3.5f \n',bulkVolume / totalPV )
I think the right calculation is totalPV / bulkVolume, but your code calculation result is normal which is <1.
So please help check the networkconstruction codes, maybe the networkconstruction  exists some little mistakes.
